# Etapa de build
FROM node:24 AS build
WORKDIR /app
COPY . .

ARG VITE_API_AUTH_URL=https://todoapp.test
ARG VITE_API_CORE_URL=https://todoapp.test

RUN yarn install && yarn build

# Etapa de producción
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
